apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.servicename }}-apiserver
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.servicename }}
  template:
    metadata:
      labels:
        app: {{ .Values.servicename }}
      # annotations:
      #   prometheus.io/scrape: "true"
      #   prometheus.io/port: "{{ .Values.metricsPort }}"
      #   prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: {{ .Values.servicename }}
        image: "{{ .Values.docker.GeneralFullImagePreamble }}{{ .Values.dimage }}:{{ .Values.tagversion }}"
        command: ["/usr/bin/apiserver"]
        args: ["start", "--db", "mongo", "--uri", "mongodb://mongodb.fledge.svc:27017"]
        ports:
        - containerPort: {{ .Values.servicePort }}
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-configmap
        {{- if .Values.mongodbcredentials }}
        volumes:
          - name: {{ .Release.Name }}-mongodb
            secret:
              secretName: {{ .Release.Name }}-mongodb
        {{- end }}
