apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.servicename }}-agent6
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.servicename }}-agent6
  template:
    metadata:
      labels:
        app: {{ .Values.servicename }}-agent6
      # annotations:
      #   prometheus.io/scrape: "true"
      #   prometheus.io/port: "{{ .Values.metricsPort }}"
      #   prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: {{ .Values.servicename }}-agent6
        image: "{{ .Values.docker.GeneralFullImagePreamble }}{{ .Values.dimage }}:{{ .Values.tagversion }}"
        command: ["/usr/bin/fledgelet"]
        args:
          - "--apiserver"
          - "{{ .Values.servicename }}-apiserver:{{ .Values.componentPorts.apiserver }}"
          - "--notifier"
          -"{{ .Values.servicename }}-notifier:{{ .Values.componentPorts.notifier }}"

        ports:
        - containerPort: {{ .Values.componentPorts.agent }}
        resources:
          requests:
            cpu: {{ .Values.resources.cpu }}
            memory: {{ .Values.resources.memory }}
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-configmap
        {{- if .Values.mongodbcredentials }}
        volumes:
          - name: {{ .Release.Name }}-mongodb
            secret:
              secretName: {{ .Release.Name }}-mongodb
        {{- end }}
