apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicename }}-apiserver
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/name: {{ .Values.servicename }}-apiserver
    tier: backend
spec:
  ports:
  - name: apiserver
    protocol: TCP
    port: {{ .Values.componentPort.apiserver }}
    targetPort: {{ .Values.componentPort.apiserver }}
  type: ClusterIP
  selector:
    app: {{ .Values.servicename }}-apiserver
