version: '3'
services:

  database:
    image: 'mongo'
    container_name: 'fledge-db'
    volumes:
      - ./mongodata:/data/db
    ports:
      - '27017-27019:27017-27019'

  notifier:
    image: 'fledge'
    container_name: 'fledge-notifier'
    command: /fledge/notifier
    ports:
      - '10101:10101'
    build:
      context: ../
      dockerfile: ./build/Dockerfile.dev
      target: build

  controller:
    image: 'fledge'
    container_name: 'fledge-controller'
    # The ""sleep 5"" is to mitigate failure to connect mongodb
    # if controler comes up before mongodb
    # TODO: refactor controller code to retry connection in case of disconnection
    command: >
      bash -c "sleep 5 &&
      /fledge/controller
      --db mongodb://fledge-db:27017
      --notifier fledge-notifier:10101"
    ports:
      - '10102:10102'
    depends_on: ['database', 'notifier']

  apiserver:
    image: 'fledge'
    container_name: 'fledge-apiserver'
    command: /fledge/apiserver start --ctlrIp fledge-controller
    ports:
      - '10100:10100'
    depends_on: ['controller']

  fledgelet:
    image: 'fledge'
    container_name: 'fledgelet'
    # NOTE: update FLEDGE_AGENT_ID based on the payload
    # to use in the t_payload collection in the DB
    environment:
      FLEDGE_AGENT_ID: f7973f5a9f16b722545d84b704e5f8be4f773a3b
    command: /fledge/fledgelet --apiserver fledge-apiserver:10100 --notifier fledge-notifier:10101
    ports:
      - '10103:10103'
    depends_on: ['apiserver', 'notifier']
